export const cardsData = [
  {
    id: 1,
    featured: true,
    category: 'mundo',
    badge: 'Mundo',
    title: 'Cúpula do G20 debate novas regras para inteligência artificial em escala global',
    excerpt: 'Líderes de 20 nações se reúnem para estabelecer um marco regulatório conjunto sobre o uso de IA em setores críticos.',
    image: 'https://resize.indiatvnews.com/en/centered/newbucket/1200_675/2024/06/lok-sabha-1719159943.jpg',
    source: 'Reuters',
    datetime: '2026-07-21T08:45',
    dateLabel: '21 jul. 2026 · 08:45',
    link: '...',
    favorited: true,
  },
  {
    id: 2,
    featured: false,
    category: 'tecnologia',
    badge: 'Tecnologia',
    title: 'OpenAI lança GPT-6 com raciocínio multimodal avançado e janela de 2M tokens',
    excerpt: 'O novo modelo promete raciocínio mais profundo, análise de vídeo em tempo real e integração nativa com ferramentas externas.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdeLwjWrWnkfP4qDO8XkGKQ958-VBQSFG3P4ST6o78KPzoQvUHP54W_f4&s=10',
    source: 'The Verge',
    datetime: '2026-07-21T10:12',
    dateLabel: '21 jul. 2026 · 10:12',
    link: '...',
    favorited: false,
  },
  {
    id: 3,
    featured: false,
    category: 'negocios',
    badge: 'Negócios',
    title: 'Banco Central eleva juros pela terceira vez consecutiva em resposta à pressão inflacionária',
    excerpt: 'A decisão unânime surpreendeu analistas que esperavam uma pausa no ciclo de aperto monetário.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjBGtbSKdpNO0L-IXFh4tl3Wlqi2YaU3l88H7pdSlT5Q&s=10',
    source: 'Financial Times',
    datetime: '2026-07-20T14:30',
    dateLabel: '20 jul. 2026 · 14:30',
    link: '...',
    favorited: false,
  },
  {
    id: 4,
    featured: false,
    category: 'esportes',
    badge: 'Esportes',
    title: 'Brasil vence nos pênaltis e avança para a semifinal da Copa América',
    excerpt: 'Em noite dramática, o goleiro Ederson defendeu três cobranças e garantiu a classificação da seleção.',
    image: 'https://s2-ge.glbimg.com/UlJsNCohtHM7b5akwn1HFQys_v4=/0x0:1500x1054/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2018/A/v/rP2uf3QIaAJl0xBzGbuA/topper-penalti.jpg',
    source: 'ESPN',
    datetime: '2026-07-20T22:05',
    dateLabel: '20 jul. 2026 · 22:05',
    link: '...',
    favorited: false,
  },
  {
    id: 5,
    featured: false,
    category: 'mundo',
    badge: 'Mundo',
    title: 'Negociações de paz no Oriente Médio colapsam após impasse nas condições de cessar-fogo',
    excerpt: 'Mediadores internacionais suspenderam as conversações após ambos os lados rejeitarem a proposta final.',
    image: 'https://www.brasildefato.com.br/wp-content/uploads/2026/04/AFP__20260408__A74F9ZQ__v1__MidRes__LebanonIsraelIranUsWar-768x512.webp',
    source: 'AL Jazeera',
    datetime: '2026-07-20T11:58',
    dateLabel: '20 jul. 2026 · 11:58',
    link: '...',
    favorited: false,
  },
  {
    id: 6,
    featured: false,
    category: 'tecnologia',
    badge: 'Tecnologia',
    title: 'Apple revela chip M5 Ultra: 40% mais rápido e com NPU dedicada para IA local',
    excerpt: 'O novo Mac Pro com M5 Ultra processa modelos de linguagem de 70B parâmetros inteiramente no dispositivo.',
    image: 'https://cdn.mos.cms.futurecdn.net/PBvaWwLt4bpaq4irFwLaEP.jpg',
    source: 'MacRumors',
    datetime: '2026-07-19T09:20',
    dateLabel: '19 jul. 2026 · 09:20',
    link: '...',
    favorited: false,
  },
  {
    id: 7,
    featured: false,
    category: 'negocios',
    badge: 'Negócios',
    title: 'Petrobras registra lucro recorde de R$ 45 bi no segundo trimestre de 2026',
    excerpt: 'Alta do petróleo e câmbio favorável impulsionam resultado que supera as estimativas de analistas em 18%.',
    image: 'https://i-invdn-com.investing.com/news/Petrobras_800x533_L_1600266768.jpg',
    source: 'Bloomberg',
    datetime: '2026-07-19T16:40',
    dateLabel: '19 jul. 2026 · 16:40',
    link: '...',
    favorited: false,
  },
];